In [1]:
import cv2 as cv
import numpy as np
import glob

In [2]:
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

In [6]:

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob('Images/imgs/*.jpg')
print(images)


['Images/imgs\\left01.jpg', 'Images/imgs\\left02.jpg', 'Images/imgs\\left03.jpg', 'Images/imgs\\left04.jpg', 'Images/imgs\\left05.jpg', 'Images/imgs\\left06.jpg', 'Images/imgs\\left07.jpg', 'Images/imgs\\left08.jpg', 'Images/imgs\\left09.jpg', 'Images/imgs\\left11.jpg', 'Images/imgs\\left12.jpg', 'Images/imgs\\left13.jpg', 'Images/imgs\\left14.jpg']


In [7]:
for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (7,6),None)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)
# Draw and display the corners
        cv.drawChessboardCorners(img, (7,6), corners2,ret)
        cv.imshow('img',img)
        cv.waitKey(2000)

cv.destroyAllWindows()



In [8]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)
img = cv.imread('Images/imgs/left12.jpg')
h,  w = img.shape[:2]
newcameramtx, roi=cv.getOptimalNewCameraMatrix(mtx,dist,(w,h),1,(w,h))
# undistort
dst = cv.undistort(img, mtx, dist, None, newcameramtx)
# crop the image
x,y,w,h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png',dst)


Camera matrix : 

[[534.15663137   0.         341.71479627]
 [  0.         534.25492559 232.05013999]
 [  0.           0.           1.        ]]
dist : 

[[-2.94269293e-01  1.23247846e-01  1.13850492e-03 -1.38021877e-04
   1.02084832e-02]]
rvecs : 

(array([[-0.43142634],
       [ 0.25379395],
       [-3.08884034]]), array([[ 0.41426793],
       [ 0.65539281],
       [-1.33764399]]), array([[-0.26431364],
       [-0.39636863],
       [-2.74760817]]), array([[-0.30060119],
       [ 0.39118933],
       [-1.4350777 ]]), array([[-0.32188588],
       [ 0.15850432],
       [-1.2418536 ]]), array([[-0.46015187],
       [-0.08996193],
       [-1.33519357]]), array([[-0.24294096],
       [ 0.35446819],
       [ 1.5301419 ]]), array([[ 0.30616402],
       [ 0.50226863],
       [-1.82846255]]), array([[-0.174203  ],
       [-0.46655317],
       [ 1.34790242]]))
tvecs : 

(array([[ 3.79289445],
       [ 0.92423107],
       [14.8637219 ]]), array([[-2.12840282],
       [ 1.86676415],
       [12.810

True